# Generated by Django 5.0.3 on 2024-03-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('finish_date', models.DateField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
